---
- name: Nginx | Installation
  include_tasks: "pkgmgr/{{ ansible_pkg_mgr }}.yml"

- name: Nginx | Ensure Nginx service is enabled and started
  service:
    name: nginx
    enabled: yes
    state: started

- name: Ntp | Ensure ntp service is enabled and started
  service:
    name: ntp
    enabled: yes
    state: started

- name: Fail2ban | Manually activate fail2ban
  command: service fail2ban start
  register: fail2ban_output

- name: Fail2ban | Ensure fail2ban service is enabled and started
  service:
    name: fail2ban
    enabled: yes
    state: started