---
- name: Nginx | Installation
  include_tasks: "pkgmgr/{{ ansible_pkg_mgr }}.yml"

- name: Nginx | Ensure Nginx service is enabled and started
  service:
    name: nginx
    enabled: yes
    state: started

- name: Ntp | Ensure ntp service is enabled and started
  service:
    name: ntpd
    enabled: yes
    state: started