---
- name: Nginx | Installation
  include_tasks: "pkgmgr/{{ ansible_pkg_mgr }}.yml"

- name: Nginx | Ensure Nginx service is enabled and started
  service:
    name: nginx
    enabled: yes
    state: started
